# Generated by Django 5.1.3 on 2024-11-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.specialist')),
            ],
        ),
    ]
