# Generated by Django 5.1.3 on 2024-11-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.service'),
        ),
    ]
