# Generated by Django 5.1.3 on 2024-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slot_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='camera_active',
            field=models.BooleanField(default=False),
        ),
    ]
