# Generated by Django 5.1.3 on 2024-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Свободен'), ('Забронирован', 'Забронирован'), ('Завершен', 'Завершен')], default='Свободен', max_length=20),
        ),
    ]
