# Generated by Django 5.1.3 on 2024-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_slot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(choices=[('1_hour', '1 час'), ('full_day', 'Полный день')], default='1_hour', max_length=20),
        ),
    ]
